--T1
USE [QL_DH_GH_ONLINE]
GO

CREATE OR ALTER PROCEDURE CAPNHAT_HOPDONG @MAHD CHAR(5), @NGAYCAPNHAT DATE 
AS
BEGIN TRAN
	DECLARE @KTRANGAY DATE
	SET @KTRANGAY = (SELECT NGAYKT FROM HOPDONG WHERE MAHD = @MAHD)
	UPDATE HOPDONG 
	SET NGAYKT = @NGAYCAPNHAT
	WHERE MAHD = @MAHD

	WAITFOR DELAY '00:00:10'
	IF (@KTRANGAY > @NGAYCAPNHAT)
	BEGIN
		ROLLBACK TRAN
		RETURN
	END
COMMIT TRAN
GO
EXEC CAPNHAT_HOPDONG 'HD469', '2021-03-09'
