USE [QL_DH_GH_ONLINE]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_INSERT_CN] @DC nvarchar(40), @SDT varchar(12), @MADT char(5)
AS
INSERT INTO CHINHANH(DIACHI, SDT, MADT) VALUES (@DC, @SDT, @MADT)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_CTDH] @MASP CHAR(5), @MADH CHAR(5), @SLSP INT
AS
INSERT INTO CTDONHANG(MASP, MADH,SLSANPHAM) VALUES (@MASP, @MADH, @SLSP)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_DGH] @MATX CHAR(5), @MADH CHAR(5), @TTGH NVARCHAR(40)
AS
INSERT INTO DONGIAOHANG VALUES (@MATX, @MADH, @TTGH)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_DH] @MAKH CHAR(5), @TTDH NVARCHAR(15), @DIACHIGH NVARCHAR(40),
							  @PHIVC MONEY, @TONGTIEN MONEY, @NGAY_DH DATE
AS
INSERT INTO DONHANG(MAKH,TTDONHANG,DIACHIGH,PHIVC,TONGTIEN, NGAY_DH) 
VALUES (@MAKH, @TTDH, @DIACHIGH, @PHIVC, @TONGTIEN, @NGAY_DH)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_DT] @TENDT NVARCHAR(40), @TP NVARCHAR(15), @QUAN NVARCHAR(50),
						@DC NVARCHAR(40), @SDT CHAR(15), @EMAIL CHAR(40),
						@MST CHAR(15), @MALH CHAR(5), @MANDD CHAR(5)
AS
INSERT INTO DOITAC(TENDOITAC,THANHPHO,QUAN,DIACHI,SDT,EMAIL,MST,MALH,MANDD)
VALUES (@TENDT, @TP, @QUAN, @DC, @SDT, @EMAIL, @MST, @MALH, @MANDD)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_HD] @MADT CHAR(5), @MACN CHAR(5), @NGAYKY DATE, @NGAYKT DATE, @PTHOAHONG FLOAT, @TTHD NVARCHAR(40)
AS
INSERT INTO HOPDONG(MADT,MACN,NGAYKY,NGAYKT,PHANTRAMHOAHONG,TINHTRANGHD)
VALUES (@MADT,@MACN,@NGAYKY,@NGAYKT,@PTHOAHONG,@TTHD)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_KH] @HOTEN NVARCHAR(40), @SDT CHAR(15), @EMAIL CHAR(40), @DC NVARCHAR(40)
AS
INSERT INTO KHACHHANG(HOTEN,SĐT,EMAIL,DIACHI) VALUES (@HOTEN,@SDT,@EMAIL,@DC)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_KVHD] @DIACHI NVARCHAR(40)
AS
INSERT INTO KHUVUCHOATDONG(DIACHIKV) VALUES (@DIACHI)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_LHVC] @TENLH NVARCHAR(40), @MT NVARCHAR(40)
AS
INSERT INTO LHVANCHUYEN(TENLOAIHANG,MOTA) VALUES (@TENLH,@MT)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_LOGIN] @USERID CHAR(5), @USERNAME CHAR(20), @PW CHAR(10), @ROLE NVARCHAR(40)
AS
INSERT INTO LOGIN(USERID,USERNAME,PASSWORD,ROLE_USER) VALUES (@USERID,@USERNAME,@PW,@ROLE)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_NDD] @HOTEN NVARCHAR(40)
AS
INSERT INTO NGUOIDAIDIEN(TENNGUOIDAIDIEN) VALUES (@HOTEN)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_INSERT_NV] @TEN NVARCHAR(40), @SDT CHAR(15), @DC NVARCHAR(50)
AS
INSERT INTO NHANVIEN(TENNV,SDT,DIACHI) VALUES (@TEN, @SDT, @DC)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[SP_INSERT_SP] @MADT CHAR(5), @TENSP NVARCHAR(40), @SLTON INT, @DONGIA MONEY
AS
INSERT INTO SANPHAM(MADT,TENSP, SLTON, DONGIA) VALUES (@MADT, @TENSP, @SLTON, @DONGIA)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_INSERT_TX] @MAKV CHAR(5), @HOTEN NVARCHAR(40), @CMND CHAR(10), 
							  @SDT CHAR(10), @DC NVARCHAR(40), @BSX NVARCHAR(10),
							  @TKNH NVARCHAR(10), @EMAIL CHAR(40), @TTDP NVARCHAR(30), @THUNHAP MONEY
AS
INSERT INTO TAIXE(MAKV,HOTEN,CMND,SĐT,DIACHI,BIENSOXE,TKNGANHANG,EMAIL,TTDONGPHITHECHAN,THUNHAP)
VALUES (@MAKV,@HOTEN,@CMND,@SDT,@DC, @BSX, @TKNH, @EMAIL,@TTDP,@THUNHAP)
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE CAPNHAT_TTHD @MAHD CHAR(5), @TTHD NVARCHAR(40)
AS
UPDATE HOPDONG
SET TINHTRANGHD = @TTHD
WHERE MAHD = @MAHD

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[THEM_TD] @TENTD NVARCHAR(40), @MASP CHAR(5)
AS
BEGIN TRAN
	DECLARE @MATD1 CHAR(5), @MADT1 CHAR(5), @MAX_MATD CHAR(5);
	SELECT @MAX_MATD = MAX(MATD) FROM THUCDON;
	SET @MATD1 = 'TD' + RIGHT('000' + CAST((CAST(SUBSTRING(@MAX_MATD, 3, 3) AS INT) + 1) AS VARCHAR), 3)
	SELECT TOP 1 @MADT1 = MADT FROM SANPHAM WHERE MASP = @MASP;
	INSERT INTO THUCDON(MATD, TENTD, MADT, MASP)
	VALUES (@MATD1, @TENTD, @MADT1, @MASP)
COMMIT TRAN

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[THEM_MON_TD] @MATD CHAR(5), @MASP CHAR(5)
AS
BEGIN TRAN
	DECLARE @TENTD NVARCHAR(40), @MADT1 CHAR(5);
	SELECT TOP 1 @TENTD = TENTD FROM THUCDON WHERE MATD = @MATD
	SELECT TOP 1 @MADT1 = MADT FROM SANPHAM WHERE MASP = @MASP;
	INSERT INTO THUCDON (MATD, TENTD, MADT, MASP)
	VALUES (@MATD, @TENTD, @MADT1, @MASP)
COMMIT TRAN

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[XOA_MON_TD] @MATD CHAR(5), @MASP CHAR(5)
AS
BEGIN TRAN
	DELETE FROM THUCDON WHERE MASP = @MASP AND MATD = @MATD
COMMIT TRAN
