USE [QL_DH_GH_ONLINE]
GO
/*CONVERSION DEADLOCK*/
/* T1 */
CREATE OR ALTER PROCEDURE CPNHAT_TTHDONG_FIX @MAHD CHAR(5), @TTHD NVARCHAR(40)
AS
BEGIN TRAN
	SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
	SELECT *
	FROM HOPDONG WITH(UPDLOCK)
	WHERE MAHD = @MAHD
	WAITFOR DELAY '00:00:10'
	
	UPDATE HOPDONG
	SET TINHTRANGHD = @TTHD
	WHERE MAHD = @MAHD
COMMIT TRAN
GO
EXEC CPNHAT_TTHDONG_FIX 'HD146', N'Hết hạn'