USE [QL_DH_GH_ONLINE]
GO
/*CONVERSION DEADLOCK*/
/* T1 */
CREATE OR ALTER PROCEDURE CPNHAT_TTHDONG @MAHD CHAR(5), @TTHD NVARCHAR(40)
AS
BEGIN TRAN
	SET TRANSACTION ISOLATION
	LEVEL REPEATABLE READ
	SELECT *
	FROM HOPDONG
	WHERE MAHD = @MAHD
	WAITFOR DELAY '00:00:10'
	
	UPDATE HOPDONG
	SET TINHTRANGHD = @TTHD
	WHERE MAHD = @MAHD
COMMIT TRAN
GO
EXEC SP_INSERT_LOGIN 'NV283', 'nv283', '123', N'Nhân viên'
--EXEC SP_INSERT_LOGIN 'NV646', 'nv646', '123', N'Nhân viên'
GO
EXEC CPNHAT_TTHDONG 'HD146', N'Hết hạn'
