USE [QL_DH_GH_ONLINE]
GO
/*CYCLE DEADLOCK*/
/* T1 */
CREATE PROCEDURE QL1_DEADLOCK @USERID CHAR(5), @PASS_NEW CHAR(10), @MATX CHAR(5), @CMND_NEW CHAR(10)
AS
BEGIN TRAN
	UPDATE LOGIN SET PASSWORD = @PASS_NEW WHERE USERID = @USERID
	WAITFOR DELAY '00:00:05'

	UPDATE TAIXE
	SET CMND = @CMND_NEW
	WHERE MATX = @MATX
COMMIT TRAN
GO

/*Demo deadlock*/
EXEC QL1_DEADLOCK 'KH001', '1234', 'TX001', '20126044'
