USE [QL_DH_GH_ONLINE]
GO
/* UNREPEATABLE READ */
/* T1 */
CREATE OR ALTER PROCEDURE TIM_NV_CN @MACN CHAR(5)
AS
BEGIN TRAN
	DECLARE @COUNT INT
	SET @COUNT = 0
	SET @COUNT = (SELECT COUNT(*) FROM NHANVIEN WHERE MACN = @MACN)
	
	WAITFOR DELAY '00:00:05'

	IF ((SELECT COUNT(*) FROM NHANVIEN WHERE MACN = @MACN) <> @COUNT)
	BEGIN
		RAISERROR(N'Khác số lượng giữa 2 lần đọc',16,1)
	END
	SELECT *
	FROM NHANVIEN 
	WHERE MACN = @MACN
COMMIT TRAN
GO
EXEC TIM_NV_CN 'CN321'